server:
  port: 9095


jwt:
  secret: "294A404E635266556A586E327235753878214125442A472D4B6150645367566B"


feign:
  client:
    product-service:
      url: http://localhost:9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart
    username: root
    password: Sebitas2515
  jpa:
    hibernate:
      ddl-auto: update

